[package]
name = "radiance"
version = "0.1.0"
authors = ["Zach Banks <zjbanks@gmail.com   >", "Eric Van Albert <eric@van.al>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "libradiance"
path = "src/lib.rs"

[[bin]]
name = "radiance"
path = "src/main.rs"

[dependencies]
futures = "0.3.8"
wgpu = "0.6.2"
rand = "0.7.3"
