[package]
name = "radiance"
version = "0.1.0"
authors = ["Zach Banks <zjbanks@gmail.com>", "Eric Van Albert <eric@van.al>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "radiance"
path = "src/lib.rs"

[[bin]]
name = "radiance"
path = "src/main.rs"

[dependencies]
futures = "0.3.8"
wgpu = "0.6.2"
rand = "0.7.3"
image = "0.23.12"
shaderc = "0.7.0"
bytemuck = {version = "1.4.1", features = ["derive"]}

[build-dependencies]
anyhow = "1.0"
fs_extra = "1.1"
shaderc = "0.7.0"
