[package]
name = "radiance"
version = "0.7.0"
authors = ["Zach Banks <zjbanks@gmail.com>", "Eric Van Albert <eric@van.al>"]
edition = "2018"

[profile.release]
debug = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
enum_dispatch = "0.3.0"
futures = "0.3.4"
log = "0.4"
serde = {version = "1", features = ["derive"]}
serde_json = "1"
strum = "0.18.0"
strum_macros = "0.18.0"
wasm-bindgen-futures = "0.4.10"
wasm-bindgen = {version = "0.2.60", features = ["serde-serialize"]}
web_logger = "0.2"
js-sys = "0.3"
wee_alloc = { version = "0.4.4", optional = true }

[dev-dependencies]
wasm-bindgen-test = "0.3"

[dependencies.web-sys]
version = "0.3.4"
features = [
    'AnalyserNode',
    'AudioContext',
    'AudioContextState',
    'AudioNode',
    'Document',
    'DomRect',
    'Element',
    'Headers',
    'HtmlCanvasElement',
    'HtmlElement',
    'HtmlVideoElement',
    'KeyboardEvent',
    'MediaDevices',
    'MediaStream',
    'MediaStreamAudioSourceNode',
    'MediaStreamConstraints',
    'Navigator',
    'Request',
    'RequestInit',
    'RequestMode',
    'Response',
    'WebGlBuffer',
    'WebGlFramebuffer',
    'WebGlProgram',
    'WebGlRenderingContext',
    'WebGlShader',
    'WebGlTexture',
    'WebGlUniformLocation',
    'Window',
    'console',
]

