[package]
name = "radiance"
version = "0.1.0"
authors = ["Zach Banks <zjbanks@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
log = "0.4"
serde = {version = "1", features = ["derive"]}
serde_json = "1"
petgraph = "0.5"
wasm-bindgen-futures = "0.4.10"
wasm-bindgen = {version = "0.2.60", features = ["serde-serialize"]}
web_logger = "0.2"
js-sys = "0.3"

# `wee_alloc` is a tiny allocator for wasm that is only ~1K in code size
# compared to the default allocator's ~10K. It is slower than the default
# allocator, however.
wee_alloc = { version = "0.4.4", optional = true }

[dev-dependencies]
wasm-bindgen-test = "0.3"

[dependencies.web-sys]
version = "0.3.4"
features = [
    'AnalyserNode',
    'AudioContext',
    'AudioNode',
    'Document',
    'DomRect',
    'Element',
    'HtmlCanvasElement',
    'HtmlElement',
    'HtmlVideoElement',
    'KeyboardEvent',
    'MediaDevices',
    'MediaStream',
    'MediaStreamConstraints',
    'MediaStreamAudioSourceNode',
    'Navigator',
    'WebGlBuffer',
    'WebGlFramebuffer',
    'WebGlProgram',
    'WebGlRenderingContext',
    'WebGl2RenderingContext',
    'WebGlShader',
    'WebGlTexture',
    'WebGlUniformLocation',
    'Window',
]

